### ISSUE TITLE
blinkenpoi geschrottet

### ISSUE THREAD

**Issue by derFux77** [overflo23/blinkenpoi#2]
Moin,

habe mir die letzte arduino ide für windows installiert und blinkenpoi.ino geladen. Dann esp8266 über den board manager und include library installiert. Ausserdem onebutton, arduinoJson (letzte 5.x), WiFiManager und Adafruit DotStar 1.1.2. Board ist LOLIN (WEMOS) D1 R2 & mini, Programmer AVRISP mk2, Port ist der, der beim Einstecken vom USB erscheint (bei mir PORT 4). Upload scheint auch zu funktionieren, nur leider will der Poi dann nicht richtig. Ich konnte mich zwar mit dem Netz Blinkenpoi verbinden und ihn so konfigurieren, er connected sich danach jedoch nicht mit dem Hotspot. Weder leuchtet die LED grün noch in irgendeiner anderen Farbe, alles bleibt dunkel...

**Comment by overflo23** [comment]
if i read you correctly you were able to compile and flash the blinkenpoi successfully.
most likely the pin numbers for clock and data on the ledstrip are swapped.

please update the source with git fetch/pull  and find these lines in blinkenpoi.ino:

#define DATAPIN    14
#define CLOCKPIN   13

on your blinkenpoi PCB is the text

GND
C
D
+5V

Check wether the ledstrip reads 

GND
CI
DI
5V

Maybe the C and D lines are swapped, there is no industry standard for these ledstrips :(

--

Afaik you are the first person on this planet besides me to compile this code.
Please expect more oddities, but stay confident, we are in this together!

**Comment by derFux77** [comment]
Thanks a lot :D
i downloaded you newest version. Additionally i followed this, step by step, which i forgot at my first try:
https://github.com/overflo23/blinkenpoi/wiki/Building-the-Firmware
together with this tutorial ( https://randomnerdtutorials.com/install-esp8266-filesystem-uploader-arduino-ide/ ), blinkenpoi seems to work again. Maybe we can change numbers, for a better cooperation fixing things, i found some bugs and maybe we can talk about how to fix this? i am the roboflower man ;)

**Comment by overflo23** [comment]
The solution was to swap the pindefinitions for clock and data
