### ISSUE TITLE
Q: Is there a wiki to explain how to dev ?

### ISSUE THREAD

**Issue by cm-t** [overflo23/blinkenpoi#4]
Hi @overflo23  :)

_We meet at 36c3 (i'm the one with inverted LED clock pin)._ _o/

I was wondering how i could upload the html/js files to the blinkenpoi hardware. I am new to arduino, I just installed the arduinoIDE, but you told me (to be able to select the right hardware) that i have to install additional stuffs before upload. Please consider talking to a newbie :angel: 

Thanks

**Comment by overflo23** [comment]
Ohai, it's complicated.

You need the wemos d1 / esp8266 boards definition for arduino.
Add this to your Boards manager/sources under preferences.
http://arduino.esp8266.com/stable/package_esp8266com_index.json


You also need the ESP8266 Sketch Data Upload plugin for Arduino (a java monster).
https://github.com/esp8266/arduino-esp8266fs-plugin



The documentation is very sparse as this is not really a newbie friendly venture at all.
I wish you all the best and good luck.
